##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Tue Mar 26 09:47:49 CST 2024]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = 1049P_makefile


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
USER/main.c \
USER/stm32f10x_it.c \
USER/system_stm32f10x.c \
CORE/core_cm3.c \
STM32F10x_FWLib/src/stm32f10x_adc.c \
STM32F10x_FWLib/src/misc.c \
STM32F10x_FWLib/src/stm32f10x_gpio.c \
STM32F10x_FWLib/src/stm32f10x_rcc.c \
STM32F10x_FWLib/src/stm32f10x_usart.c \
STM32F10x_FWLib/src/stm32f10x_tim.c \
STM32F10x_FWLib/src/stm32f10x_dma.c \
SYSTEM/delay/delay.c \
SYSTEM/sys/sys.c \
SYSTEM/usart/usart_dma.c \
HARDWARE/SECRET_KEY/secret_key.c \
HARDWARE/GPIO/gpio.c \
HARDWARE/TIMER/timer.c \
HARDWARE/STMFLASH/stmflash.c \
HARDWARE/MCUControl/Common.c \
HARDWARE/MCUControl/MCU_HOST.c \
HARDWARE/MCUControl/MCU_POWER.c \
HARDWARE/DS28E01/DS28E01.c \
HARDWARE/DS28E01/SHA.c \
HARDWARE/MCUControl/MCU_MicroRF.c \
HARDWARE/MCUControl/MCU_Liti.c \
HARDWARE/MCUControl/MCU_Fractional.c \
HARDWARE/ADC/adc20190609.c \
HARDWARE/TASK/Task.c \
HARDWARE/SOFTTIMER/softtimer.c \
SYSTEM/SERIAL_PORT/serial_protocol.c \
SYSTEM/SERIAL_PORT/serial_rx_tx.c \
HARDWARE/CRC16/crc16.c \
MALLOC/heap_malloc.c \
RTT/SEGGER_RTT.c \
RTT/SEGGER_RTT_printf.c

# ASM sources
ASM_SOURCES =  \
CORE/startup_stm32f103xe.s
#CORE/startup_stm32f10x_hd.s

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F10X_HD \
-DUSE_STDPERIPH_DRIVER


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IUSER \
-ICORE \
-ISTM32F10x_FWLib/inc \
-ISYSTEM/delay \
-ISYSTEM/sys \
-ISYSTEM/usart \
-IHARDWARE \
-IHARDWARE/TIMER \
-IHARDWARE/GPIO \
-IHARDWARE/DMA \
-IMALLOC \
-IHARDWARE/MCUControl \
-IHARDWARE/DS28E01 \
-IHARDWARE/STMFLASH \
-IHARDWARE/ADC \
-IRTT \
-IHARDWARE/SOFTTIMER \
-IHARDWARE/TASK \
-IHARDWARE/CRC16 \
-ISYSTEM/SERIAL_PORT \
-IHARDWARE/SECRET_KEY


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F103VCTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***